import type { VisualConfig, Theme } from "../types";

export const defaultVisualConfig: VisualConfig = {
  cover: {
    position: "left",
    offsetX: 0,
    offsetY: -40,
    widthPercent: 22,
    borderRadius: 16,
    shadowIntensity: 0.6,
  },
  lyrics: {
    position: "right",
    offsetX: 0,
    offsetY: -40,
    widthPercent: 36,
    verticalAlign: "center",
    textAlign: "left",
    fontFamily: "Inter, Helvetica Neue, Arial, sans-serif",
    activeFontSize: 32,
    inactiveFontSize: 24,
    lineSpacing: 56,
    letterSpacing: 0,
    activeColor: "#ffffff",
    activeWeight: 600,
    inactiveOpacity: 0.25,
    futureOpacity: 0.4,
    scrollSpeed: 0.35,
    visibleLines: 5,
  },
  title: {
    fontFamily: "Inter, Helvetica Neue, Arial, sans-serif",
    fontSize: 28,
    fontWeight: 600,
    color: "#ffffff",
    opacity: 1,
    position: "below-cover",
    offsetX: 0,
    offsetY: 32,
  },
  artist: {
    fontFamily: "Inter, Helvetica Neue, Arial, sans-serif",
    fontSize: 18,
    fontWeight: 400,
    color: "rgba(255,255,255,0.45)",
    opacity: 1,
    offsetY: 6,
  },
  background: {
    type: "blurred-cover",
    blurAmount: 80,
    brightness: 0.18,
    overlayOpacity: 0.35,
    solidColor: "#0a0a0f",
    gradientFrom: "#1a1a2e",
    gradientTo: "#0a0a0f",
    gradientAngle: 135,
  },
  video: {
    width: 1920,
    height: 1080,
    fps: 30,
  },
  lyricAnimation: {
    enabled: false,
    activeColor: "#6c5ce7",
    completedColor: "#888888",
    inactiveColor: "#ffffff",
    colorMode: "current-line" as const,
    transitionDuration: 2,
  },
};

export const builtInThemes: Theme[] = [
  {
    name: "cinematic",
    label: "Cinematic",
    config: { ...defaultVisualConfig },
  },
  {
    name: "minimal",
    label: "Minimal",
    config: {
      cover: {
        position: "center",
        offsetX: 0,
        offsetY: -160,
        widthPercent: 25,
        borderRadius: 8,
        shadowIntensity: 0.3,
      },
      lyrics: {
        position: "center",
        offsetX: 0,
        offsetY: 120,
        widthPercent: 50,
        verticalAlign: "top",
        textAlign: "center",
        fontFamily: "Georgia, Times New Roman, serif",
        activeFontSize: 30,
        inactiveFontSize: 22,
        lineSpacing: 52,
        letterSpacing: 0,
        activeColor: "#ffffff",
        activeWeight: 400,
        inactiveOpacity: 0.2,
        futureOpacity: 0.35,
        scrollSpeed: 0.4,
        visibleLines: 4,
      },
      title: {
        fontFamily: "Georgia, Times New Roman, serif",
        fontSize: 22,
        fontWeight: 400,
        color: "#ffffff",
        opacity: 0.8,
        position: "bottom-center",
        offsetX: 0,
        offsetY: -60,
      },
      artist: {
        fontFamily: "Georgia, Times New Roman, serif",
        fontSize: 16,
        fontWeight: 400,
        color: "rgba(255,255,255,0.4)",
        opacity: 1,
        offsetY: 8,
      },
      background: {
        type: "solid",
        blurAmount: 60,
        brightness: 0.15,
        overlayOpacity: 0,
        solidColor: "#0d0d0d",
        gradientFrom: "#1a1a2e",
        gradientTo: "#0a0a0f",
        gradientAngle: 135,
      },
      video: {
        width: 1920,
        height: 1080,
        fps: 30,
      },
      lyricAnimation: {
        enabled: false,
        activeColor: "#6c5ce7",
        completedColor: "#888888",
        inactiveColor: "#ffffff",
        colorMode: "current-line" as const,
        transitionDuration: 2,
      },
    },
  },
  {
    name: "classic",
    label: "Classic",
    config: {
      cover: {
        position: "left",
        offsetX: -20,
        offsetY: 0,
        widthPercent: 28,
        borderRadius: 4,
        shadowIntensity: 0.8,
      },
      lyrics: {
        position: "right",
        offsetX: 20,
        offsetY: 0,
        widthPercent: 40,
        verticalAlign: "center",
        textAlign: "left",
        fontFamily: "Helvetica Neue, Helvetica, Arial, sans-serif",
        activeFontSize: 36,
        inactiveFontSize: 26,
        lineSpacing: 60,
        letterSpacing: 0,
        activeColor: "#f0e68c",
        activeWeight: 700,
        inactiveOpacity: 0.3,
        futureOpacity: 0.5,
        scrollSpeed: 0.3,
        visibleLines: 5,
      },
      title: {
        fontFamily: "Helvetica Neue, Helvetica, Arial, sans-serif",
        fontSize: 34,
        fontWeight: 700,
        color: "#ffffff",
        opacity: 1,
        position: "top-left",
        offsetX: 80,
        offsetY: 50,
      },
      artist: {
        fontFamily: "Helvetica Neue, Helvetica, Arial, sans-serif",
        fontSize: 20,
        fontWeight: 400,
        color: "rgba(255,255,255,0.6)",
        opacity: 1,
        offsetY: 8,
      },
      background: {
        type: "blurred-cover",
        blurAmount: 60,
        brightness: 0.22,
        overlayOpacity: 0.4,
        solidColor: "#0a0a0f",
        gradientFrom: "#1a1a2e",
        gradientTo: "#0a0a0f",
        gradientAngle: 180,
      },
      video: {
        width: 1920,
        height: 1080,
        fps: 30,
      },
      lyricAnimation: {
        enabled: false,
        activeColor: "#f0e68c",
        completedColor: "#888888",
        inactiveColor: "#ffffff",
        colorMode: "current-line" as const,
        transitionDuration: 2,
      },
    },
  },
];

export function mergeConfig(
  base: VisualConfig,
  partial: Partial<VisualConfig> | undefined
): VisualConfig {
  if (!partial) return base;
  return {
    cover: { ...base.cover, ...partial.cover },
    lyrics: { ...base.lyrics, ...partial.lyrics },
    title: { ...base.title, ...partial.title },
    artist: { ...base.artist, ...partial.artist },
    background: { ...base.background, ...partial.background },
    video: { ...base.video, ...partial.video },
    lyricAnimation: { ...base.lyricAnimation, ...partial.lyricAnimation },
  };
}
